# Generated by Django 5.1.6 on 2025-03-30 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commons', '0003_userprofile_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='profile',
        ),
    ]
