# Generated by Django 5.1.6 on 2025-03-31 11:13

import commons.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commons', '0005_alter_profile_birthday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(default='default.jpg', upload_to=commons.models.profile_picture_upload_to),
        ),
    ]
