# Generated by Django 5.1.6 on 2025-03-02 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='letter',
            name='category',
            field=models.CharField(default='', max_length=50),
        ),
    ]
