# Generated by Django 5.1.6 on 2025-03-02 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_letter_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='letter',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
