# Generated by Django 5.1.6 on 2025-03-03 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_letter_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='letter',
            name='category',
            field=models.CharField(choices=[('past', '과거'), ('today', '오늘'), ('tomorrow', '미래')], default='오늘', max_length=20),
        ),
    ]
