# Generated by Django 5.1.6 on 2025-03-03 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_letter_category'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Letter',
            new_name='Letters',
        ),
    ]
