# Generated by Django 5.1.6 on 2025-03-04 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_rename_letter_letters'),
    ]

    operations = [
        migrations.AlterField(
            model_name='letters',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
