# Generated by Django 5.1.6 on 2025-03-07 07:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_letters_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='letters',
            name='category',
            field=models.CharField(choices=[('past', '과거'), ('today', '오늘'), ('future', '미래')], default='오늘', max_length=20),
        ),
        migrations.CreateModel(
            name='LetterRoutine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('routine_type', models.CharField(choices=[('weekly', '매주'), ('monthly', '매월')], max_length=10)),
                ('day_of_week', models.CharField(blank=True, max_length=10, null=True)),
                ('time', models.TimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
