# Generated by Django 5.1.6 on 2025-03-07 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_letters_category_letterroutine'),
    ]

    operations = [
        migrations.AddField(
            model_name='letters',
            name='mood',
            field=models.CharField(choices=[('happy', '행복'), ('sad', '슬픔'), ('angry', '화남'), ('worried', '고민'), ('diary', '일기')], default='diary', max_length=10),
        ),
    ]
