# Generated by Django 5.1.6 on 2025-03-13 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_alter_letters_mood'),
    ]

    operations = [
        migrations.AddField(
            model_name='letterroutine',
            name='day_of_month',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='letterroutine',
            name='day_of_week',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
