# Generated by Django 5.1.6 on 2025-03-14 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_letterroutine_day_of_month_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='letterroutine',
            name='title',
            field=models.CharField(default='편지 루틴', max_length=200),
        ),
    ]
