# Generated by Django 5.1.6 on 2025-03-14 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_letterroutine_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='letterroutine',
            name='day_of_week',
            field=models.CharField(blank=True, null=True),
        ),
    ]
