# Generated by Django 5.1.6 on 2025-03-14 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_specialdateroutine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='letterroutine',
            name='routine_type',
            field=models.CharField(blank=True, choices=[('weekly', '매주'), ('monthly', '매월')], max_length=10, null=True),
        ),
    ]
