# Generated by Django 5.1.6 on 2025-03-15 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_alter_letterroutine_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='letterroutine',
            name='time',
            field=models.TimeField(null=True),
        ),
    ]
