# Generated by Django 5.1.6 on 2025-03-17 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_alter_letterroutine_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='letters',
            name='open_date',
            field=models.DateField(),
        ),
    ]
