# Generated by Django 5.1.6 on 2025-03-19 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0021_letters_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='letters',
            name='status',
            field=models.CharField(choices=[('read', '읽음'), ('opened', '개봉 가능'), ('unopened', '개봉 전')], default='개봉 후'),
        ),
        migrations.AlterField(
            model_name='letters',
            name='category',
            field=models.CharField(choices=[('past', '과거'), ('today', '오늘'), ('future', '미래')], default='future', max_length=20),
        ),
    ]
