# Generated by Django 5.1.6 on 2025-03-19 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0022_letters_status_alter_letters_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='letters',
            name='status',
        ),
    ]
