# Generated by Django 5.1.6 on 2025-04-04 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0026_letterroutine_emotion'),
    ]

    operations = [
        migrations.AddField(
            model_name='letters',
            name='emotion',
            field=models.CharField(blank=True, choices=[('happy', '기쁨'), ('sad', '슬픔'), ('angry', '분노'), ('worried', '불안'), ('neutral', '중립')], max_length=10, null=True),
        ),
    ]
