# Generated by Django 5.1.6 on 2025-04-04 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0027_letters_emotion'),
    ]

    operations = [
        migrations.AddField(
            model_name='letters',
            name='analyzed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
