# Generated by Django 5.1.6 on 2025-05-07 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0029_alter_letters_emotion'),
    ]

    operations = [
        migrations.AddField(
            model_name='letters',
            name='detailed_mood',
            field=models.CharField(blank=True, choices=[('ecstasy', '희열'), ('satisfaction', '만족'), ('gratitude', '감사'), ('excitement', '설렘'), ('loneliness', '외로움'), ('loss', '상실감'), ('regret', '후회'), ('annoyance', '짜증'), ('rage', '분개'), ('resentment', '억울함'), ('fear', '두려움'), ('nervousness', '긴장'), ('restlessness', '초조'), ('romance', '로맨스'), ('friendship', '우정'), ('respect', '존경')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='letterroutine',
            name='emotion',
            field=models.CharField(blank=True, choices=[('joy', '기쁨'), ('sadness', '슬픔'), ('anger', '분노'), ('anxiety', '불안'), ('love', '사랑'), ('neutral', '중립')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='letters',
            name='emotion',
            field=models.CharField(blank=True, choices=[('joy', '기쁨'), ('sadness', '슬픔'), ('anger', '분노'), ('anxiety', '불안'), ('love', '사랑'), ('neutral', '중립')], max_length=30, null=True),
        ),
    ]
