# Generated by Django 5.1.6 on 2025-05-07 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0032_recommendationfeedback'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RecommendationFeedback',
        ),
    ]
